version: 0.2

phases:
  build:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_URL
      - docker build -t $ECR_URL/$IMAGE_NAME:$IMAGE_TAG .
      - docker push $ECR_URL/$IMAGE_NAME:$IMAGE_TAG
